# Generated by Django 3.1.8 on 2021-04-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='имя на русском')),
                ('image', models.ImageField(null=True, upload_to='pokemon_pic', verbose_name='изображение покемона')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='имя на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='имя на японском')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='эолюционировал из')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Появился на карте в ')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Исчез с карты в ')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='атака')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='покемон')),
            ],
        ),
    ]
