# Generated by Django 3.1.8 on 2021-04-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20210421_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='эволюционировал из'),
        ),
        migrations.CreateModel(
            name='PokemonElement_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название элемента')),
                ('strong_against', models.ManyToManyField(to='pokemon_entities.PokemonElement_Type', verbose_name='силен против')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='element', to='pokemon_entities.PokemonElement_Type', verbose_name='тип элемента'),
        ),
    ]
