# Generated by Django 3.1.8 on 2021-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20210421_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelement_type',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='название элемента на английском'),
        ),
    ]
