# Generated by Django 3.1.8 on 2021-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonelement_type_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelement_type',
            name='strong_against',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElement_Type', verbose_name='силен против'),
        ),
    ]
