# Generated by Django 3.1.8 on 2021-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemonelement_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, upload_to='pokemon_pic', verbose_name='изображение покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonelement_type',
            name='image',
            field=models.ImageField(blank=True, upload_to='element_pic', verbose_name='изображение элемента'),
        ),
    ]
