# Generated by Django 3.1.8 on 2021-04-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20210421_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonElement_Type',
            new_name='PokemonElementType',
        ),
    ]
