# Generated by Django 3.1.8 on 2021-04-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20210421_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='image',
        ),
    ]
