# Generated by Django 3.1.8 on 2021-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_remove_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(null=True, upload_to='element_pic', verbose_name='изображение элемента'),
        ),
    ]
