# Generated by Django 3.1.8 on 2021-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='изображение элемента'),
        ),
    ]
